<a href="https://colab.research.google.com/github/IrfhanAhmedh/Reservoir-Simulator-1D-2D-/blob/main/1D_Reservoir_Simulation_Explicit_NonTransmissbilityform.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Solving 1D homogenous Reservoir using explicit method and without using Transmissiblity form

In [ ]:
import numpy as np
pie=0.2
l=10000
k=20
ct=10**(-6)
mu=1
number_of_grids=10
dt=1
pb=2000
dx=l/number_of_grids
alpha=0.006328*k/(pie*mu*ct)
eeta=alpha*dt/(dx*dx)

In [ ]:
print(eeta)

0.6328


In [ ]:
#initial conditon
pi=np.arange(10)*0+1100
pi=pi.reshape(10,1)


In [ ]:
arr=np.arange(100).reshape(10,10)*0    #intialising an array (left hand side)
arr=arr.astype(float)

In [ ]:
# Boundary condition
arr[0][0]=1+3*eeta     #left side dirchlet
arr[9][9]=1+eeta       #right side newman


In [ ]:
for i in range(1,10):       #Assigning values for left side of equation
 arr[i][i]=1+2*eeta
for i in range(9):        
 arr[i][i+1]=-eeta
 arr[i+1][i]=-eeta

In [ ]:
q=np.arange(10)*0
q=q.reshape(10,1)
q=q.astype(float)
q[0][0]=2*eeta*pb

In [ ]:
print(q)

[[2531.2]
 [   0. ]
 [   0. ]
 [   0. ]
 [   0. ]
 [   0. ]
 [   0. ]
 [   0. ]
 [   0. ]
 [   0. ]]


In [ ]:
for i in range(1,4): # for 3 days only Note:Range can be increased to increase time
 b=pi+q   # Right hand side of the equation
 pn1=np.linalg.solve(arr,b)
 print('at time = ',i)
 print(pn1)
 pi=pn1


at time =  1
[[1521.05434903]
 [1228.54602595]
 [1139.17617624]
 [1111.71558102]
 [1102.76886226]
 [1098.19771595]
 [1090.77845959]
 [1068.7866046 ]
 [ 997.46890354]
 [ 764.12355321]]
at time =  2
[[1692.68157678]
 [1349.26348471]
 [1196.61255249]
 [1134.72706946]
 [1109.20613832]
 [1093.85789377]
 [1071.65152314]
 [1019.21927317]
 [ 888.45685342]
 [ 585.42507506]]
at time =  3
[[1771.9753753 ]
 [1441.23238146]
 [1255.82582371]
 [1163.99270341]
 [1118.40742438]
 [1087.36273645]
 [1046.05389346]
 [ 964.29367614]
 [ 795.73573911]
 [ 480.65265306]]
